FROM mirror.gcr.io/library/node:22-alpine

WORKDIR /app

COPY frontend/package.json ./
COPY frontend/package-lock.json ./

RUN npm ci

COPY frontend/ ./

EXPOSE 5001

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5001"]