services:
  nginx:
    build:
      context: .
      dockerfile: infra/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - backend
      - frontend
    ports:
      #- "80:80"
      - "443:443"
    networks:
      - trancendence
    volumes:
      - ./tools/:/etc/nginx/ssl/
      - nginx-logs:/var/log/nginx
    restart: always

  database:
    build:
      context: .
      dockerfile: infra/postgres/Dockerfile
    container_name: database
    env_file:
      - .env
    #environment:
     # POSTGRES_USER: ${POSTGRES_USER:-myuser}
     # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
     # POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
     # DATABASE_URL: postgresql://${POSTGRES_USER:-myuser}:${POSTGRES_PASSWORD:-mypassword}@database:5432/${POSTGRES_DB:-mydatabase}
    ports:
      - "5432:5432"
    networks:
      - trancendence
    # volumes:
    #   - db-volume:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - trancendence
    #volumes:
    #  - wp-volume:/var/www/
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - trancendence
    restart: always

  redis:
    build:
      context: .
      dockerfile: infra/redis/Dockerfile
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - trancendence
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.27
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - trancendence
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.27
    depends_on: [elasticsearch]
    ports: ["5044:5044"]
    volumes:
      - ./infra/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - trancendence
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.27
    depends_on: 
      - nginx
      - logstash
    volumes:
      - ./nginx-logs:/var/log/nginx:ro
      - ./infra/elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - trancendence
    restart: always
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.27
    depends_on: [elasticsearch]
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: ["5601:5601"]
    networks:
      - trancendence
    restart: always

volumes:
  esdata:
  nginx-logs:

networks:
  trancendence:
    driver: bridge