// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { expand } from "dotenv-expand";
import { defineConfig } from "prisma/config";

// Allow DATABASE_URL to use ${VAR} references from .env.
expand(loadEnv({ path: [".env", "../.env"], override: false }));

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
