filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/frontend_access.log
  json.keys_under_root: true
  json.add_error_key: true
  fields:
    server: nginx

output.logstash:
  hosts: ["logstash:5044"]